"""EDT: Upgrade question

Revision ID: 490bc258efe3
Revises: fcaf791c9dfa
Create Date: 2024-09-07 01:47:11.846263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '490bc258efe3'
down_revision: Union[str, None] = 'fcaf791c9dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'quiz_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'quiz_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
